server:
  port: 8085
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /leyou148
    username: leyou148
    password: leyou

ly:
  sms:
    accessKeyID: LTAI4G1s5PbuN7CPXsBhHeLt # 你自己的accessKeyId
    accessKeySecret: uf5fI1sQUJsMPGIKRZXTh0wnqOAqqt # 你自己的AccessKeySecret
    endpoint: dysmsapi.aliyuncs.com
    signName: leyou商城 # 签名名称
    verifyCodeTemplate: SMS_201716517 # 模板名称
    code: code # 短信模板中验证码的占位符