server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

ly:
  upload:
    imagePath: D:\leyou_projects\javaee148\software\nginx-1.16.0\html\brand-logo
    imageUrl: http://localhost/brand-logo/

  oss:
    accessKeyId: LTAI4G1s5PbuN7CPXsBhHeLt
    accessKeySecret: uf5fI1sQUJsMPGIKRZXTh0wnqOAqqt
    host: http://image.leyou.com # 访问oss的域名，很重要bucket + endpoint
    endpoint: oss-cn-guangzhou.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: "" # 保存到bucket的某个子目录
    expireTime: 20 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M