server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://manage.leyou.com"
              - "http://www.leyou.com"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 360000
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - HEAD
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      routes:
        - id: item-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://item-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/item/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
        - id: upload-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://upload-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/upload/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
        - id: search-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://search-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/search/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
        - id: user-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://user-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/user/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
        - id: auth-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://auth-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/auth/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
        - id: cart-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://cart-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/cart/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
        - id: order-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://order-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/order/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=1
        - id: pay-service   # 路由id,可以随意写
          # 代理的服务地址；lb表示负载均衡(从nacos中获取具体服务)
          uri: lb://order-service
          # 路由断言，可以配置映射路径
          predicates:
            - Path=/api/pay/**
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
  task:
    scheduling:
      pool:
        size: 1 #一般有几个定时任务就开启几个线程             -
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #设置API网关中路由转发请求的HystrixCommand执行超时时间
            timeoutInMilliseconds: 5000

ly:
  jwt:
    pubKeyPath: D:\leyou_projects\javaee148\software\rsa-key\rsa-key.pub # 公钥地址
    cookie:
      cookieName: LY_TOKEN # cookie名称
    app:
      serviceName: api-gateway
      secret: api-gateway
  filter:
    allowPaths:
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/pay